---
- hosts: all
  roles:
    - role: matic-insurance.hostname
      fqdn_hostname: '{{ inventory_hostname }}'
      tags: ['hostname']

    - role: amaabca.loggly_tls
      loggly:
        refresh_unicorn: false
        logrotate: false
        application:
          environment: 'env'
      tags: ['logger']

    - role: monit
      monit_add_user_to_group: '{{ allow_monit_for_user | default(omit) }}'
      tags: ['monit']
