---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Ensure everything is installed
      raw: apt-get install python-minimal aptitude -y

- hosts: all
  roles:
    - role: update
      tags: ['update']

    - role: matic-insurance.hostname
      fqdn_hostname: '{{ inventory_hostname }}'
      tags: ['hostname']

    - role: geerlingguy.ntp
      tags: ['ntp']

- hosts: app
  pre_tasks:
    - name: Gather facts from BigBrother
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['bigbrother'] }}"
      tags: ['app', 'metrics']
  roles:
    - role: amaabca.loggly_tls
      loggly:
        refresh_unicorn: false
        logrotate: false
        application:
          environment: 'env'
      tags: ['logger']

    - role: monit

      tags: ['monit']

    - role: metrics
      metrics_influxdb_host: "http://{{ hostvars[groups['bigbrother'][0]]['ansible_default_ipv4']['address'] }}:8086"
      tags: ['metrics']

    - role: app
      tags: ['app']

- hosts: bigbrother
  roles:
    - role: angstwad.docker_ubuntu
      docker_group_members: "{{ [docker_group_member | default(None)] | select('string') | list }}"
      tags: ['docker']

    - role: monitoring
      tags: ['monitoring']
