---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Ensure everything is installed
      raw: apt-get install python-minimal aptitude -y

- hosts: all
  roles:
    - role: update
      tags: ['update']

    - role: matic-insurance.hostname
      fqdn_hostname: '{{ inventory_hostname }}'
      tags: ['hostname']

    - role: geerlingguy.ntp

- hosts: app
  roles:
    - role: amaabca.loggly_tls
      loggly:
        refresh_unicorn: false
        logrotate: false
        application:
          environment: 'env'
      tags: ['logger']

    - role: monit
      monit_add_user_to_group: '{{ application_user }}'
      monit_app_prefix: 'diverst-'
      monit_app_root: '{{ application_root }}/'
      monit_app_user: '{{ application_user }}'
      monit_app_run_prefix: '{{ application_run_prefix }}'
      tags: ['monit']

    - role: metrics
      tags: ['metrics']

- hosts: bigbrother
  roles:
    - role: angstwad.docker_ubuntu
