/*
 *
 * HomePage constants
 *
 */

export const GET_QUESTIONNAIRE_BY_TOKEN_BEGIN = 'app/SignUp/GET_QUESTIONNAIRE_BY_TOKEN_BEGIN';
export const GET_QUESTIONNAIRE_BY_TOKEN_SUCCESS = 'app/SignUp/GET_QUESTIONNAIRE_BY_TOKEN_SUCCESS';
export const GET_QUESTIONNAIRE_BY_TOKEN_ERROR = 'app/SignUp/GET_QUESTIONNAIRE_BY_TOKEN_ERROR';

export const SUBMIT_RESPONSE_BEGIN = 'app/SignUp/SUBMIT_RESPONSE_BEGIN';
export const SUBMIT_RESPONSE_SUCCESS = 'app/SignUp/SUBMIT_RESPONSE_SUCCESS';
export const SUBMIT_RESPONSE_ERROR = 'app/SignUp/SUBMIT_RESPONSE_ERROR';

export const POLL_RESPONSE_UNMOUNT = 'app/SignUp/POLL_RESPONSE_UNMOUNT';
