/*
 *
 * PollResponse constants
 *
 */

export const GET_QUESTIONNAIRE_BY_TOKEN_BEGIN = 'app/PollResponse/GET_QUESTIONNAIRE_BY_TOKEN_BEGIN';
export const GET_QUESTIONNAIRE_BY_TOKEN_SUCCESS = 'app/PollResponse/GET_QUESTIONNAIRE_BY_TOKEN_SUCCESS';
export const GET_QUESTIONNAIRE_BY_TOKEN_ERROR = 'app/PollResponse/GET_QUESTIONNAIRE_BY_TOKEN_ERROR';

export const SUBMIT_RESPONSE_BEGIN = 'app/PollResponse/SUBMIT_RESPONSE_BEGIN';
export const SUBMIT_RESPONSE_SUCCESS = 'app/PollResponse/SUBMIT_RESPONSE_SUCCESS';
export const SUBMIT_RESPONSE_ERROR = 'app/PollResponse/SUBMIT_RESPONSE_ERROR';

export const POLL_RESPONSE_UNMOUNT = 'app/PollResponse/POLL_RESPONSE_UNMOUNT';
