/*
 *
 * Group constants
 *
 */

export const GET_GROUPS_BEGIN = 'app/Group/GET_GROUPS_BEGIN';
export const GET_GROUPS_SUCCESS = 'app/Group/GET_GROUPS_SUCCESS';
export const GET_GROUPS_ERROR = 'app/Group/GET_GROUPS_ERROR';

export const GET_COLORS_BEGIN = 'app/Group/GET_COLORS_BEGIN';
export const GET_COLORS_SUCCESS = 'app/Group/GET_COLORS_SUCCESS';
export const GET_COLORS_ERROR = 'app/Group/GET_COLORS_ERROR';

export const GET_ANNUAL_BUDGETS_BEGIN = 'app/Group/GET_ANNUAL_BUDGETS_BEGIN';
export const GET_ANNUAL_BUDGETS_SUCCESS = 'app/Group/GET_ANNUAL_BUDGETS_SUCCESS';
export const GET_ANNUAL_BUDGETS_ERROR = 'app/Group/GET_ANNUAL_BUDGETS_ERROR';

export const GET_GROUP_BEGIN = 'app/Group/GET_GROUP_BEGIN';
export const GET_GROUP_SUCCESS = 'app/Group/GET_GROUP_SUCCESS';
export const GET_GROUP_ERROR = 'app/Group/GET_GROUP_ERROR';

export const CREATE_GROUP_BEGIN = 'app/Group/CREATE_GROUP_BEGIN';
export const CREATE_GROUP_SUCCESS = 'app/Group/CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'app/Group/CREATE_GROUP_ERROR';

export const UPDATE_GROUP_BEGIN = 'app/Group/UPDATE_GROUP_BEGIN';
export const UPDATE_GROUP_SUCCESS = 'app/Group/UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_ERROR = 'app/Group/UPDATE_GROUP_ERROR';

export const UPDATE_GROUP_SETTINGS_BEGIN = 'app/Group/UPDATE_GROUP_SETTINGS_BEGIN';
export const UPDATE_GROUP_SETTINGS_SUCCESS = 'app/Group/UPDATE_GROUP_SETTINGS_SUCCESS';
export const UPDATE_GROUP_SETTINGS_ERROR = 'app/Group/UPDATE_GROUP_SETTINGS_ERROR';

export const UPDATE_GROUP_POSITION_BEGIN = 'app/Group/UPDATE_GROUP_POSITION_BEGIN';
export const UPDATE_GROUP_POSITION_SUCCESS = 'app/Group/UPDATE_GROUP_POSITION_SUCCESS';
export const UPDATE_GROUP_POSITION_ERROR = 'app/Group/UPDATE_GROUP_POSITION_ERROR';

export const DELETE_GROUP_BEGIN = 'app/Group/DELETE_GROUP_BEGIN';
export const DELETE_GROUP_SUCCESS = 'app/Group/DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'app/Group/DELETE_GROUP_ERROR';

export const CARRY_BUDGET_BEGIN = 'app/Group/CARRY_BUDGET_BEGIN';
export const CARRY_BUDGET_SUCCESS = 'app/Group/CARRY_BUDGET_SUCCESS';
export const CARRY_BUDGET_ERROR = 'app/Group/CARRY_BUDGET_ERROR';

export const RESET_BUDGET_BEGIN = 'app/Group/RESET_BUDGET_BEGIN';
export const RESET_BUDGET_SUCCESS = 'app/Group/RESET_BUDGET_SUCCESS';
export const RESET_BUDGET_ERROR = 'app/Group/RESET_BUDGET_ERROR';

export const GROUP_LIST_UNMOUNT = 'app/Group/GROUP_LIST_UNMOUNT';
export const GROUP_FORM_UNMOUNT = 'app/Group/GROUP_FORM_UNMOUNT';

export const JOIN_GROUP_BEGIN = 'app/Group/JOIN_GROUP_BEGIN';
export const JOIN_GROUP_SUCCESS = 'app/Group/JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_ERROR = 'app/Group/JOIN_GROUP_ERROR';

export const LEAVE_GROUP_BEGIN = 'app/Group/LEAVE_GROUP_BEGIN';
export const LEAVE_GROUP_SUCCESS = 'app/Group/LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_ERROR = 'app/Group/LEAVE_GROUP_ERROR';

export const GROUP_CATEGORIZE_UNMOUNT = 'app/Group/GROUP_CATEGORIZE_UNMOUNT';

export const GROUP_CATEGORIZE_BEGIN = 'app/Group/GROUP_CATEGORIZE_BEGIN';
export const GROUP_CATEGORIZE_SUCCESS = 'app/Group/GROUP_CATEGORIZE_SUCCESS';
export const GROUP_CATEGORIZE_ERROR = 'app/Group/GROUP_CATEGORIZE_ERROR';

export const JOIN_SUBGROUPS_BEGIN = 'app/Group/JOIN_SUBGROUP_BEGIN';
export const JOIN_SUBGROUPS_SUCCESS = 'app/Group/JOIN_SUBGROUP_SUCCESS';
export const JOIN_SUBGROUPS_ERROR = 'app/Group/JOIN_SUBGROUP_ERROR';
