/*
 *
 * Group constants
 *
 */

export const GET_GROUPS_BEGIN = 'app/Group/GET_GROUPS_BEGIN';
export const GET_GROUPS_SUCCESS = 'app/Group/GET_GROUPS_SUCCESS';
export const GET_GROUPS_ERROR = 'app/Group/GET_GROUPS_ERROR';

export const GET_GROUP_BEGIN = 'app/Group/GET_GROUP_BEGIN';
export const GET_GROUP_SUCCESS = 'app/Group/GET_GROUP_SUCCESS';
export const GET_GROUP_ERROR = 'app/Group/GET_GROUP_ERROR';

export const CREATE_GROUP_BEGIN = 'app/Group/CREATE_GROUP_BEGIN';
export const CREATE_GROUP_SUCCESS = 'app/Group/CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'app/Group/CREATE_GROUP_ERROR';

export const UPDATE_GROUP_BEGIN = 'app/Group/UPDATE_GROUP_BEGIN';
export const UPDATE_GROUP_SUCCESS = 'app/Group/UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_ERROR = 'app/Group/UPDATE_GROUP_ERROR';

export const UPDATE_GROUP_SETTINGS_BEGIN = 'app/Group/UPDATE_GROUP_SETTINGS_BEGIN';
export const UPDATE_GROUP_SETTINGS_SUCCESS = 'app/Group/UPDATE_GROUP_SETTINGS_SUCCESS';
export const UPDATE_GROUP_SETTINGS_ERROR = 'app/Group/UPDATE_GROUP_SETTINGS_ERROR';

export const DELETE_GROUP_BEGIN = 'app/Group/DELETE_GROUP_BEGIN';
export const DELETE_GROUP_SUCCESS = 'app/Group/DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'app/Group/DELETE_GROUP_ERROR';

export const GROUP_LIST_UNMOUNT = 'app/Group/GROUP_LIST_UNMOUNT';
export const GROUP_FORM_UNMOUNT = 'app/Group/GROUP_FORM_UNMOUNT';
export const GROUP_CATEGORIZE_UNMOUNT = 'app/Group/GROUP_CATEGORIZE_UNMOUNT';

export const GROUP_CATEGORIZE_BEGIN = 'app/Group/GROUP_CATEGORIZE_BEGIN';
export const GROUP_CATEGORIZE_SUCCESS = 'app/Group/GROUP_CATEGORIZE_SUCCESS';
export const GROUP_CATEGORIZE_ERROR = 'app/Group/GROUP_CATEGORIZE_ERROR';
