eslint_executable: '/home/ubuntu/TeamDiverst/diverst-development/client/node_modules/.bin/eslint'
files_to_lint: 'client/'
cmd_line_opts:  '--config client/.eslintrc.js --ignore-path client/.eslintignore'
