Rails:
  Enabled: true
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/BlockDelimiters:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 300
Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 300
Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50

AllCops:
  Exclude:
    - bin/**/*
  TargetRubyVersion: 2.3