version: '2'
services:
  app:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/diverst
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: elasticsearch
      REWARDS_ENABLED: "true"
    links:
      - mysql
      - redis
      - elasticsearch
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  elasticsearch:
    image: elasticsearch:2.3.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml -e development
    links:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - .:/diverst
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: elasticsearch
volumes:
  mysql:
  redis:
  elasticsearch:
  diverst:
