version: '2'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/diverst
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql2://user:pass@mysql:3306"
    links:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "root"

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - mysql
      - redis
    volumes:
      - .:/diverst
