---
- name: Gather EC2 facts
  ec2_metadata_facts:

- name: Retrieve all ec2 tags on the instance
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    access_key: '{{ metrics_access_key }}'
    secret_key: '{{ metrics_secret_key }}'
    state: list
  register: my_ec2_tags

- include_role:
    name: rossmcdonald.telegraf
  vars:
    telegraf_aws_tags: false
    telegraf_tags: '{{ my_ec2_tags.tags | combine(metrics_extra_tags) }}'
    telegraf_influxdb_urls:
      - '{{ metrics_influxdb_host }}'
    telegraf_influxdb_database: '{{ metrics_influxdb_database }}'
    telegraf_plugins:
      - name: mem
        options:
          fielddrop:
            - "active"
            - "buffered"
            - "cached"
            - "free"
            - "inactive"
            - "used"
            - "used_percent"
      - name: system
        options:
          fielddrop: ["n_users","uptime_format"]
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_guest"
            - "time_guest_nice"
            - "time_irq"
            - "time_nice"
            - "time_softirq"
            - "time_steal"
            - "usage_guest"
            - "usage_guest_nice"
            - "usage_irq"
            - "usage_nice"
            - "usage_softirq"
            - "usage_steal"
      - name: disk
        options:
          mountpoints:
            - "/"
          fielddrop: ["used", "inodes_used"]

      - name: processes
      - name: swap
        options:
          fielddrop: ["free","total"]
      - name: nstat
        options:
          interval: "2s"
          proc_net_netstat: "" # this is of interest.
          fieldpass: ["IpExtOutOctets","IpExtInOctets"]
