---
- name: Gather EC2 facts
  ec2_metadata_facts:

- name: Retrieve all ec2 tags on the instance
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    access_key: '{{ metrics_access_key }}'
    secret_key: '{{ metrics_secret_key }}'
    state: list
  register: my_ec2_tags

- include_role:
    name: rossmcdonald.telegraf
  vars:
    telegraf_aws_tags: false
    telegraf_tags: '{{ my_ec2_tags.tags | combine(metrics_extra_tags) }}'
    telegraf_influxdb_urls:
      - '{{ metrics_influxdb_host }}'
    telegraf_influxdb_database: '{{ metrics_influxdb_database }}'
    telegraf_plugins:
      - name: mem
      - name: system
      - name: cpu
        options:
          percpu: "true"
          totalcpu: "true"
          fielddrop:
            - "time_*"
      - name: disk
        options:
          mountpoints:
            - "/"
      - name: diskio
        options:
          skip_serial_number: "true"
      # - name: net
      #   options:
      #     interfaces:
      #       - "{{ ansible_default_ipv4.interface }}"
