---
- name: Gather EC2 facts
  ec2_metadata_facts:

- include_role:
    name: rossmcdonald.telegraf
  vars:
    telegraf_configuration_template: 'my-telegraf.conf.j2'
    telegraf_aws_tags: false
    telegraf_tags:
      instance_id: '{{ ansible_ec2_instance_id }}'
    telegraf_plugins:
      - name: mem
      - name: system
      - name: cpu
        options:
          percpu: "true"
          totalcpu: "true"
          fielddrop:
            - "time_*"
      - name: disk
        options:
          mountpoints:
            - "/"
      - name: diskio
        options:
          skip_serial_number: "true"
      # - name: net
      #   options:
      #     interfaces:
      #       - "{{ ansible_default_ipv4.interface }}"
