/*
 *
 * News constants
 *
 */

export const GET_NEWS_ITEMS_BEGIN = 'app/News/GET_NEWS_ITEMS_BEGIN';
export const GET_NEWS_ITEMS_SUCCESS = 'app/News/GET_NEWS_ITEMS_SUCCESS';
export const GET_NEWS_ITEMS_ERROR = 'app/News/GET_NEWS_ITEMS_ERROR';

export const GET_NEWS_ITEM_BEGIN = 'app/News/GET_NEWS_ITEM_BEGIN';
export const GET_NEWS_ITEM_SUCCESS = 'app/News/GET_NEWS_ITEM_SUCCESS';
export const GET_NEWS_ITEM_ERROR = 'app/News/GET_NEWS_ITEM_ERROR';

export const CREATE_GROUP_MESSAGE_BEGIN = 'app/News/CREATE_GROUP_MESSAGE_BEGIN ';
export const CREATE_GROUP_MESSAGE_SUCCESS = 'app/News/CREATE_GROUP_MESSAGE_SUCCESS';
export const CREATE_GROUP_MESSAGE_ERROR = 'app/News/CREATE_GROUP_MESSAGE_ERROR';

export const UPDATE_GROUP_MESSAGE_BEGIN = 'app/News/UPDATE_GROUP_MESSAGE_BEGIN ';
export const UPDATE_GROUP_MESSAGE_SUCCESS = 'app/News/UPDATE_GROUP_MESSAGE_SUCCESS';
export const UPDATE_GROUP_MESSAGE_ERROR = 'app/News/UPDATE_GROUP_MESSAGE_ERROR';

export const DELETE_GROUP_MESSAGE_BEGIN = 'app/News/DELETE_GROUP_MESSAGE_BEGIN ';
export const DELETE_GROUP_MESSAGE_SUCCESS = 'app/News/DELETE_GROUP_MESSAGE_SUCCESS';
export const DELETE_GROUP_MESSAGE_ERROR = 'app/News/DELETE_GROUP_MESSAGE_ERROR';

export const CREATE_GROUP_MESSAGE_COMMENT_BEGIN = 'app/News/CREATE_GROUP_MESSAGE_COMMENT_BEGIN ';
export const CREATE_GROUP_MESSAGE_COMMENT_SUCCESS = 'app/News/CREATE_GROUP_MESSAGE_COMMENT_SUCCESS';
export const CREATE_GROUP_MESSAGE_COMMENT_ERROR = 'app/News/CREATE_GROUP_MESSAGE_COMMENT_ERROR';

export const DELETE_GROUP_MESSAGE_COMMENT_BEGIN = 'app/News/DELETE_GROUP_MESSAGE_COMMENT_BEGIN ';
export const DELETE_GROUP_MESSAGE_COMMENT_SUCCESS = 'app/News/DELETE_GROUP_MESSAGE_COMMENT_SUCCESS';
export const DELETE_GROUP_MESSAGE_COMMENT_ERROR = 'app/News/DELETE_GROUP_MESSAGE_COMMENT_ERROR';


export const NEWS_FEED_UNMOUNT = 'app/News/NEWS_FEED_UNMOUNT';

export const CREATE_NEWSLINK_BEGIN = 'app/News/CREATE_NEWSLINK_BEGIN';
export const CREATE_NEWSLINK_SUCCESS = 'app/News/CREATE_NEWSLINK_SUCCESS';
export const CREATE_NEWSLINK_ERROR = 'app/News/CREATE_NEWSLINK_ERROR';
export const UPDATE_NEWSLINK_BEGIN = 'app/News/CREATE_NEWSLINK_ERROR';
export const UPDATE_NEWSLINK_SUCCESS = 'app/News/UPDATE_NEWSLINK_SUCCESS';
export const UPDATE_NEWSLINK_ERROR = 'app/News/UPDATE_NEWSLINK_ERROR';
export const DELETE_NEWSLINK_BEGIN = 'app/News/DELETE_NEWSLINK_BEGIN';
export const DELETE_NEWSLINK_SUCCESS = 'app/News/DELETE_NEWSLINK_SUCCESS';
export const DELETE_NEWSLINK_ERROR = 'app/News/DELETE_NEWSLINK_ERROR';
export const CREATE_NEWSLINK_COMMENT_BEGIN = 'app/News/CREATE_NEWSLINK_COMMENT_BEGIN';
export const CREATE_NEWSLINK_COMMENT_SUCCESS = 'app/News/CREATE_NEWSLINK_COMMENT_SUCCESS';
export const CREATE_NEWSLINK_COMMENT_ERROR = 'app/News/CREATE_NEWSLINK_COMMENT_ERROR';

export const DELETE_NEWSLINK_COMMENT_BEGIN = 'app/News/DELETE_NEWSLINK_COMMENT_BEGIN';
export const DELETE_NEWSLINK_COMMENT_SUCCESS = 'app/News/DELETE_NEWSLINK_COMMENT_SUCCESS';
export const DELETE_NEWSLINK_COMMENT_ERROR = 'app/News/DELETE_NEWSLINK_COMMENT_ERROR';

export const CREATE_SOCIALLINK_BEGIN = 'app/News/CREATE_SOCIALLINK_BEGIN';
export const CREATE_SOCIALLINK_SUCCESS = 'app/News/CREATE_SOCIALLINK_SUCCESS';
export const CREATE_SOCIALLINK_ERROR = 'app/News/CREATE_SOCIALLINK_ERROR';
export const UPDATE_SOCIALLINK_BEGIN = 'app/News/UPDATE_SOCIALLINK_BEGIN';
export const UPDATE_SOCIALLINK_SUCCESS = 'app/News/UPDATE_SOCIALLINK_SUCCESS';
export const UPDATE_SOCIALLINK_ERROR = 'app/News/UPDATE_SOCIALLINK_ERROR';
export const CREATE_SOCIALLINK_COMMENT_BEGIN = 'app/News/CREATE_SOCIALLINK_COMMENT_BEGIN';
export const CREATE_SOCIALLINK_COMMENT_SUCCESS = 'app/News/CREATE_SOCIALLINK_COMMENT_SUCCESS';
export const CREATE_SOCIALLINK_COMMENT_ERROR = 'app/News/CREATE_SOCIALLINK_COMMENT_ERROR';
export const DELETE_SOCIALLINK_BEGIN = 'app/News/DELETE_SOCIALLINK_BEGIN';
export const DELETE_SOCIALLINK_SUCCESS = 'app/News/DELETE_SOCIALLINK_SUCCESS';
export const DELETE_SOCIALLINK_ERROR = 'app/News/DELETE_SOCIAL_ERROR';
