/*
 *
 * SignUp constants
 *
 */

export const GET_USER_BY_TOKEN_BEGIN = 'app/SignUp/GET_USER_BY_TOKEN_BEGIN';
export const GET_USER_BY_TOKEN_SUCCESS = 'app/SignUp/GET_USER_BY_TOKEN_SUCCESS';
export const GET_USER_BY_TOKEN_ERROR = 'app/SignUp/GET_USER_BY_TOKEN_ERROR';

export const GET_ONBOARDING_GROUPS_BEGIN = 'app/SignUp/GET_ONBOARDING_GROUPS_BEGIN';
export const GET_ONBOARDING_GROUPS_SUCCESS = 'app/SignUp/GET_ONBOARDING_GROUPS_SUCCESS';
export const GET_ONBOARDING_GROUPS_ERROR = 'app/SignUp/GET_ONBOARDING_GROUPS_ERROR';

export const SUBMIT_PASSWORD_BEGIN = 'app/SignUp/SUBMIT_PASSWORD_BEGIN';
export const SUBMIT_PASSWORD_SUCCESS = 'app/SignUp/SUBMIT_PASSWORD_SUCCESS';
export const SUBMIT_PASSWORD_ERROR = 'app/SignUp/SUBMIT_PASSWORD_ERROR';

export const SIGN_UP_UNMOUNT = 'app/SignUp/SIGN_UP_UNMOUNT';
