/*
 *
 * Folder constants
 *
 */

export const GET_FOLDERS_BEGIN = 'app/Folder/GET_FOLDERS_BEGIN';
export const GET_FOLDERS_SUCCESS = 'app/Folder/GET_FOLDERS_SUCCESS';
export const GET_FOLDERS_ERROR = 'app/Folder/GET_FOLDERS_ERROR';

export const GET_FOLDER_BEGIN = 'app/Folder/GET_FOLDER_BEGIN';
export const GET_FOLDER_SUCCESS = 'app/Folder/GET_FOLDER_SUCCESS';
export const GET_FOLDER_ERROR = 'app/Folder/GET_FOLDER_ERROR';

export const CREATE_FOLDER_BEGIN = 'app/Folder/CREATE_FOLDER_BEGIN ';
export const CREATE_FOLDER_SUCCESS = 'app/Folder/CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_ERROR = 'app/Folder/CREATE_FOLDER_ERROR';

export const UPDATE_FOLDER_BEGIN = 'app/Folder/UPDATE_FOLDER_BEGIN ';
export const UPDATE_FOLDER_SUCCESS = 'app/Folder/UPDATE_FOLDER_SUCCESS';
export const UPDATE_FOLDER_ERROR = 'app/Folder/UPDATE_FOLDER_ERROR';

export const DELETE_FOLDER_BEGIN = 'app/Folder/DELETE_FOLDER_BEGIN ';
export const DELETE_FOLDER_SUCCESS = 'app/Folder/DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_ERROR = 'app/Folder/DELETE_FOLDER_ERROR';

export const VALIDATE_FOLDER_PASSWORD_BEGIN = 'app/Folder/VALIDATE_FOLDER_PASSWORD_BEGIN ';
export const VALIDATE_FOLDER_PASSWORD_SUCCESS = 'app/Folder/VALIDATE_FOLDER_PASSWORD_SUCCESS';
export const VALIDATE_FOLDER_PASSWORD_ERROR = 'app/Folder/VALIDATE_FOLDER_PASSWORD_ERROR';

export const FOLDERS_UNMOUNT = 'app/Folder/FOLDERS_UNMOUNT';

export const ARCHIVE_RESOURCE_BEGIN = '';
export const ARCHIVE_RESOURCE_SUCCESS = '';
export const ARCHIVE_RESOURCE_ERROR ='';

export const GET_RESOURCES_BEGIN = 'app/Resource/GET_RESOURCES_BEGIN';
export const GET_RESOURCES_SUCCESS = 'app/Resource/GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_ERROR = 'app/Resource/GET_RESOURCES_ERROR';

export const GET_RESOURCE_BEGIN = 'app/Resource/GET_RESOURCE_BEGIN';
export const GET_RESOURCE_SUCCESS = 'app/Resource/GET_RESOURCE_SUCCESS';
export const GET_RESOURCE_ERROR = 'app/Resource/GET_RESOURCE_ERROR';

export const CREATE_RESOURCE_BEGIN = 'app/Resource/CREATE_RESOURCE_BEGIN ';
export const CREATE_RESOURCE_SUCCESS = 'app/Resource/CREATE_RESOURCE_SUCCESS';
export const CREATE_RESOURCE_ERROR = 'app/Resource/CREATE_RESOURCE_ERROR';

export const UPDATE_RESOURCE_BEGIN = 'app/Resource/UPDATE_RESOURCE_BEGIN ';
export const UPDATE_RESOURCE_SUCCESS = 'app/Resource/UPDATE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCE_ERROR = 'app/Resource/UPDATE_RESOURCE_ERROR';

export const DELETE_RESOURCE_BEGIN = 'app/Resource/DELETE_RESOURCE_BEGIN ';
export const DELETE_RESOURCE_SUCCESS = 'app/Resource/DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_ERROR = 'app/Resource/DELETE_RESOURCE_ERROR';

export const RESOURCES_UNMOUNT = 'app/Resource/RESOURCES_UNMOUNT';
