---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: Add PPA with a newer python
  apt_repository:
    repo: 'ppa:jonathonf/python-2.7'
    codename: trusty
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Upgrade python2.7
  apt:
    name: python
    state: latest
