---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: Upgrade python2.7
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python
    - python-urllib3
    - python-pip
    - python-dev
    - libffi-dev
    - libssl-dev

- name: Remove distro python packages
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - python-openssl
    - python-pyasn1
    - python-boto

- name: Update setuptools via pip
  pip: name=setuptools state=latest

- name: Install python packages
  pip: name={{ item }} state=latest
  with_items:
    - boto
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
