#!/bin/bash

# Bootstrap script for client, creates resources needed for terraform & deployment
# - create s3 bucket with versioning & at-rest encryption - used for terraform state & eb deployment bundles
# - create dynamodb table for state locking
# - create KMS key - used for secrets management with chamber & parameter key store
# Usage: ./bootstrap-backend <env-name>

BUCKET_POSTFIX="$(head /dev/urandom | tr -dc a-z | head -c 8)"
CLIENT_NAME="$1"
BUCKET_NAME="$CLIENT_NAME-$BUCKET_POSTFIX"

# Exit on error
set -e

# Create S3 bucket with encryption & versioning
aws s3api create-bucket \
  --bucket "$BUCKET_NAME" \

aws s3api put-bucket-encryption \
  --bucket "$BUCKET_NAME" \
  --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

aws s3api put-bucket-versioning \
  --bucket "$BUCKET_NAME" \
  --versioning-configuration Status=Enabled

# Create dynamodb table for state locking
#  - creates primary key LockID - mandatory to work with terraform
aws dynamodb create-table \
  --table-name "$CLIENT_NAME-tf-statelock" \
  --attribute-definitions AttributeName=LockID,AttributeType=S \
  --key-schema AttributeName=LockID,KeyType=HASH \
  --billing-mode PAY_PER_REQUEST

# Create KMS key & alias
#   - alias must be 'parameter_store_key' for chamber to find it
key_id=$(aws kms create-key --description 'Secrets management' --output text | cut -f8)
aws kms create-alias \
  --alias-name alias/parameter_store_key \
  --target-key-id "$key_id"

# Outputs
echo "$BUCKET_NAME"
