#!/bin/bash

# Bundle API, upload to S3 & create a EB app version
# Usage: ./create-app-version <aws-profile> <eb-app-name> <app-version-label> <bucket-name>

PROFILE=$1
EB_APP_NAME=$2
APP_NAME="api-diverst-$VERSION_LABEL.zip"
VERSION_LABEL=$3
BUNDLE_BUCKET_NAME=$4
RELEASE_BRANCH='HEAD' # TEMP - for development purposes

# Exit on error
set -e

if [ ! -d '.git' ]; then
  echo 'Error - not in app root'
  exit 1
fi

mkdir -p build

# Create app bundle
git archive --format=zip --output="./build/$APP_NAME" "$RELEASE_BRANCH"

# Copy app bundle to S3 - assumes bucket exists - should be created by bootstrap-backend
aws s3 cp "./build/$APP_NAME" "s3://$BUNDLE_BUCKET_NAME" --profile "$PROFILE"

# Create app version
aws elasticbeanstalk create-application-version \
  --profile "$PROFILE" \
  --application-name "$EB_APP_NAME" \
  --version-label "$VERSION_LABEL" \
  --source-bundle S3Bucket="$BUNDLE_BUCKET_NAME",S3Key="$APP_NAME"
