#!/bin/bash

# Create a backend Elastic Beanstalk app version
#   - assumes app has been bundled via `bundle-backend` script using same version label
#   - upload backend bundle to S3 & create an EB app version
# Usage: ./create-app-version <env-name> <app-version-label> <bucket-name>

ENV_NAME=$1
VERSION_LABEL=$2
BUNDLE_BUCKET_NAME=$3
APP_NAME="api-diverst-$VERSION_LABEL.zip"

# Exit on error
set -e

if [ ! -d '.git' ] || [ ! -d 'build' ]; then
  echo 'Error - not in app root or build directory missing'
  exit 1
fi

# Upload app bundle to S3 - assumes bucket exists
aws s3 cp "./build/$APP_NAME" "s3://$BUNDLE_BUCKET_NAME"

# Create app version
aws elasticbeanstalk create-application-version \
  --application-name "$ENV_NAME" \
  --version-label "$VERSION_LABEL" \
  --source-bundle S3Bucket="$BUNDLE_BUCKET_NAME",S3Key="$APP_NAME"
