#!/bin/bash

# Build & deploy frontend
# Must be run from app root
# Usage: ./create-app-version <frontend-bucket>

FRONTEND_BUCKET=$1

# Exit on error
set -e

if [ ! -d '.git' ]; then
  echo 'Error - not in app root'
  exit 1
fi

cd client/

# Build frontend (npm install is handled separately)
npm run build

aws s3 sync --cache-control 'max-age=604800' --exclude index.html build/ "s3://$FRONTEND_BUCKET"
aws s3 sync --cache-control 'no-cache' build/ "s3://$FRONTEND_BUCKET"
