#!/bin/bash

# Deploy a given app version for the given environment
# Usage: ./deploy-app-version <env-name> <app-version-label>

ENV_NAME=$1
EB_VERSION_LABEL=$2

# Deploy app version
aws elasticbeanstalk update-environment \
  --environment-name "$ENV_NAME-env" \
  --version-label "$EB_VERSION_LABEL"
