#!/bin/bash

# Initialize database on a new client's backend
#  - SSH's into one of the ec2 instances, jumping through the bastion host,
#    we are running rails commands on the database, so which ec2 instance & the
#    fact that they are ephemeral is irrelevant
# Usage: ./init-db <bastion-url> <eb-url> <key-path>

USER=ec2-user
BASTION_URL=$1
EB_URL=$2
SSH_KEY=$3

# Setup ssh key forwarding so we can authenticate with the instances
eval "$(ssh-agent -s)"
ssh-add "$SSH_KEY"

# Run a small script to initialize the database
#  - load the schema
#  - run database migration task (mainly for posterity)
#  - run production seeds - sets up some preliminary models
#  - generate a API key & set it via a task, we do this so we can output it for later usage
ssh -A -i "$SSH_KEY" -J "$USER@$BASTION_URL" "$USER@$EB_URL" -o ConnectTimeout=1800 -T << "EOF"
  EB_DEPLOY_DIR=$(sudo /opt/elasticbeanstalk/bin/get-config container -k app_deploy_dir)
  API_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

  cd "$EB_DEPLOY_DIR"

  rails db:schema:load
  rails db:migrate
  rails db:seed

  rails "set_api_key[$API_KEY]"
  echo "$API_KEY"
EOF
