#!/bin/bash

# Usage: ./load-client-env <environment>

ENVIRONMENT=$1

# Exit on error
set -e

if [ ! -d '.git' ]; then
  echo 'Error - not in app root'
  exit 1
fi

# Load variables from parameter key store into environment variables
# Create client .env file based on environment variable values
client_config=$(chamber export --format dotenv "$ENVIRONMENT")

echo 'Deploying with client configuration:'
echo "$client_config"

echo "$client_config" > client/.env
echo 'ENVIRONMENT="development"' >> client/.env
