---
dependencies:
  - role: rvm_io.ruby
    rvm1_rubies: ['ruby-2.3.0']
    rvm1_user: '{{ application_user }}'
    tags: ['ruby']

  - role: geerlingguy.nodejs
    nodejs_version: "8.x"
    nodejs_install_npm_user: '{{ application_user }}'
    nodejs_npm_global_packages:
      - name: bower
