---
# Required:
monit_app_prefix: 'unspecified'
monit_app_root: 'unspecified/' # should end with a trailing slash /
monit_app_user: 'unspecified'

# Optional:
monit_app_run_prefix:
monit_app_run_as_user: '/usr/bin/sudo -iu {{ monit_app_user }} /bin/bash -c'
monit_app_env: production
monit_app_run_env: >-
  cd {{ monit_app_root }}current &&
  export RACK_ENV={{ monit_app_env }} &&
  export RAILS_ENV={{ monit_app_env }} &&
  {{ monit_app_run_prefix }} bundle exec


# this doesn't work since monit is very strict about permissions,
# and only root is able to run `monit status`
monit_add_user_to_group:
monit_cli_password: 'ysDQkwLjLmwjzdhXum9pDzGbMaLUt6BSauPTW6F9nE4J6BGx'
monit_check_interval: 60

monit_puma_workers: 0
monit_puma_total_memory_percent: 30
monit_puma_memory_per_worker: '{{ (monit_puma_total_memory_percent / (monit_puma_workers + 1)) | round | int }} %'
monit_puma_memory_cycles: 5

monit_puma_pid_path: 'shared/tmp/pids/puma.pid'
monit_puma_pid_abspath: '{{ monit_app_root }}{{ monit_puma_pid_path }}'

monit_puma_config_path: 'shared/config/puma.rb'
monit_puma_config_abspath: '{{ monit_app_root }}{{ monit_puma_config_path }}'

monit_puma_state_path: 'shared/tmp/pids/puma.state'
monit_puma_state_abspath: '{{ monit_app_root }}{{ monit_puma_state_path }}'

monit_puma_start_command: >-
  {{ monit_app_run_as_user }} '{{ monit_app_run_env }}
  puma -C {{ monit_puma_config_abspath }} --daemon'

monit_puma_stop_command: >-
  {{ monit_app_run_as_user }} '{{ monit_app_run_env }}
  pumactl -S {{ monit_puma_state_abspath }} -F {{ monit_puma_config_abspath }} stop'

monit_puma_worker_pattern: 'puma: cluster worker %WID%:'
monit_puma_stop_worker_command: >-
  /usr/bin/env pkill -f '{{ monit_puma_worker_pattern }}'

monit_sidekiq_processes: 1

monit_sidekiq_pid_path: 'shared/tmp/pids/sidekiq-%i%.pid'
monit_sidekiq_pid_abspath: '{{ monit_app_root }}{{ monit_sidekiq_pid_path }}'
monit_sidekiq_config_path: 'current/config/sidekiq.yml'
monit_sidekiq_config_abspath: '{{ monit_app_root }}{{ monit_sidekiq_config_path }}'
monit_sidekiq_exit_timeout: 180

monit_sidekiq_memory_per_worker: '50 %'
monit_sidekiq_memory_cycles: 5

monit_sidekiq_start_command: >-
  {{ monit_app_run_as_user }} '{{ monit_app_run_env }}
  sidekiq -i %i% -P {{ monit_sidekiq_pid_abspath }} -e production -L /dev/null
  -C {{ monit_sidekiq_config_abspath }} -d'

monit_sidekiq_stop_command: >-
  {{ monit_app_run_as_user }} '{{ monit_app_run_env }}
  sidekiqctl stop {{ monit_sidekiq_pid_abspath }} {{ monit_sidekiq_exit_timeout }}'

monit_clockwork_pid_dir: 'shared/tmp/pids'
monit_clockwork_pid_path: '{{ monit_clockwork_pid_dir }}/clockworkd.clock.pid'
monit_clockwork_log_dir: 'shared/log'

monit_clockwork_start_command: >-
  {{ monit_app_run_as_user }} '{{ monit_app_run_env }}
  clockworkd -c clock.rb --dir=.
  --pid-dir={{ monit_app_root }}{{ monit_clockwork_pid_dir }}
  --log-dir={{ monit_app_root }}{{ monit_clockwork_log_dir }}
  --log start'

monit_clockwork_stop_command: >-
  {{ monit_app_run_as_user }} '{{ monit_app_run_env }}
  clockworkd -c clock.rb --dir=.
  --pid-dir={{ monit_app_root }}{{ monit_clockwork_pid_dir }}
  --log-dir={{ monit_app_root }}{{ monit_clockwork_log_dir }}
  --log stop'
