---
- name: Install monit package
  apt:
    name: monit

- name: Generate monitrc
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    mode: 0600
  notify:
    - restart monit

- name: Create monit group
  group:
    name: monit
    state: present
  when: monit_add_user_to_group != ""

- name: Add user to the monit group
  user:
    name: '{{ monit_add_user_to_group }}'
    groups: monit
    append: yes
  when: monit_add_user_to_group != ""

- name: Generate a config for Puma
  template:
    src: puma.conf.j2
    dest: /etc/monit/conf.d/puma.conf
    mode: 0600
  when: monit_watch_puma
  notify:
    - restart monit

- name: Generate a config for Sidekiq
  template:
    src: sidekiq.conf.j2
    dest: /etc/monit/conf.d/sidekiq.conf
    mode: 0600
  when: monit_watch_sidekiq
  notify:
    - restart monit

- name: Generate a config for Clockwork
  template:
    src: clockwork.conf.j2
    dest: /etc/monit/conf.d/clockwork.conf
    mode: 0600
  when: monit_watch_clockwork
  notify:
    - restart monit

- name: Start monit service
  service:
    name: monit
    state: started
    enabled: yes
