/*
 *
 * Mentorship constants
 *
 */

export const GET_USER_MENTORS_BEGIN = 'app/Mentorship/GET_USER_MENTORS_BEGIN';
export const GET_USER_MENTORS_SUCCESS = 'app/Mentorship/GET_USER_MENTORS_SUCCESS';
export const GET_USER_MENTORS_ERROR = 'app/Mentorship/GET_USER_MENTORS_ERROR';

export const GET_AVAILABLE_MENTORS_BEGIN = 'app/Mentorship/GET_AVAILABLE_MENTORS_BEGIN';
export const GET_AVAILABLE_MENTORS_SUCCESS = 'app/Mentorship/GET_AVAILABLE_MENTORS_SUCCESS';
export const GET_AVAILABLE_MENTORS_ERROR = 'app/Mentorship/GET_AVAILABLE_MENTORS_ERROR';

export const GET_USER_MENTEES_BEGIN = 'app/Mentorship/GET_USER_MENTEES_BEGIN';
export const GET_USER_MENTEES_SUCCESS = 'app/Mentorship/GET_USER_MENTEES_SUCCESS';
export const GET_USER_MENTEES_ERROR = 'app/Mentorship/GET_USER_MENTEES_ERROR';

export const GET_AVAILABLE_MENTEES_BEGIN = 'app/Mentorship/GET_MENTORSHIP_USER_BEGIN';
export const GET_AVAILABLE_MENTEES_SUCCESS = 'app/Mentorship/GET_MENTORSHIP_USER_SUCCESS';
export const GET_AVAILABLE_MENTEES_ERROR = 'app/Mentorship/GET_MENTORSHIP_USER_ERROR';

export const MENTORSHIP_USER_UNMOUNT = 'app/Mentorship/MENTORSHIP_USER_UNMOUNT';
export const MENTORSHIP_MENTORS_UNMOUNT = 'app/Mentorship/MENTORSHIP_MENTORS_UNMOUNT';
