---
- name: Run InfluxDB container
  docker_container:
    name:  '{{ influxdb_container_name }}'
    image: '{{ influxdb_docker_image }}'
    volumes:
      - '{{ influxdb_volume_name }}:/var/lib/influxdb'
    network_mode: 'host'
    restart_policy: always
  register: influxdb_container

- name: Wait for InfluxDB start
  wait_for:
    port: 8086
  when: influxdb_container.changed

- name: Install python influxdb
  apt: name=python-influxdb state=present

- name: Create InfluxDB databases
  influxdb_database:
    database_name: "{{ item }}"
  with_items:
    - '{{ metrics_influxdb_system_db }}'
    - '{{ metrics_influxdb_rails_db }}'
    - '{{ metrics_influxdb_sidekiq_db }}'

- name: Run Grafana container
  docker_container:
    name:  '{{ grafana_container_name }}'
    image: '{{ grafana_docker_image }}'
    ports:
      - '{{ grafana_binding_port }}:3000'
    env:
      GF_SECURITY_ADMIN_PASSWORD: '{{ grafana_admin_password }}'
    restart_policy: always
  register: grafana_container

- name: Wait for Grafana start
  wait_for:
    port: '{{ grafana_binding_port }}'
  when: grafana_container.changed

- name: Add InfluxDB source to Grafana
  grafana_datasource:
    name: '{{ item | capitalize }}'
    grafana_url: 'http://localhost:{{ grafana_binding_port }}'
    grafana_password: '{{ grafana_admin_password }}'
    ds_type: influxdb
    url: http://{{ ansible_default_ipv4.address }}:8086
    database: '{{ item }}'
    state: present
  with_items:
    - '{{ metrics_influxdb_system_db }}'
    - '{{ metrics_influxdb_rails_db }}'
    - '{{ metrics_influxdb_sidekiq_db }}'

- name: Add Linux host dashboard to Grafana
  grafana_dashboard:
    grafana_url: 'http://localhost:{{ grafana_binding_port }}'
    grafana_password: '{{ grafana_admin_password }}'
    path: '{{ role_path }}/files/linux_host.json'
    slug: 'linux-host'
    state: present
  when: false
