---
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622

- name: Add debug symbols repo
  apt_repository:
    repo: deb http://ddebs.ubuntu.com {{ item }} main restricted universe multiverse
    state: present
  with_items:
    - '{{ ansible_distribution_release }}'
    - '{{ ansible_distribution_release }}-updates'
    - '{{ ansible_distribution_release }}-proposed'

- name: Install necessary dependencies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items:
    - libmysqlclient20
    - libmysqlclient20-dbgsym
    - libmysqlclient-dev

- name: Create an application folder
  file:
    path: '{{ application_root }}'
    state: directory
    owner: '{{ application_user }}'

- name: Render application.yml config
  template:
    src: '{{ application_yml }}'
    dest: '{{ application_root }}/shared/config/application.yml'

- name: Render database.yml
  template:
    src: 'database.yml.j2'
    dest: '{{ application_root }}/shared/config/database.yml'

- name: Render puma.rb
  template:
    src: 'puma.rb.j2'
    dest: '{{ application_root }}/shared/config/puma.rb'

- name: Make bower visible to Capistrano
  file:
    src: '/usr/local/lib/npm/bin/bower'
    dest: '/usr/local/bin/bower'
    state: link

- name: Redirect 80 to 3000 port
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: '{{ ansible_default_ipv4.interface }}'
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 3000
  notify:
    - persist iptables
