/*
 *
 * User constants
 *
 */

export const GET_USERS_BEGIN = 'app/User/GET_USERS_BEGIN';
export const GET_USERS_SUCCESS = 'app/User/GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'app/User/GET_USERS_ERROR';

export const GET_USER_BEGIN = 'app/User/GET_USER_BEGIN';
export const GET_USER_SUCCESS = 'app/User/GET_USER_SUCCESS';
export const GET_USER_ERROR = 'app/User/GET_USER_ERROR';

export const GET_USER_POSTS_BEGIN = 'app/User/GET_USER_POSTS_BEGIN';
export const GET_USER_POSTS_SUCCESS = 'app/User/GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_ERROR = 'app/User/GET_USER_POSTS_ERROR';

export const GET_USER_EVENTS_BEGIN = 'app/User/GET_USER_EVENTS_BEGIN';
export const GET_USER_EVENTS_SUCCESS = 'app/User/GET_USER_EVENTS_SUCCESS';
export const GET_USER_EVENTS_ERROR = 'app/User/GET_USER_EVENTS_ERROR';

export const GET_USER_DOWNLOADS_BEGIN = 'app/User/GET_USER_DOWNLOADS_BEGIN';
export const GET_USER_DOWNLOADS_SUCCESS = 'app/User/GET_USER_DOWNLOADS_SUCCESS';
export const GET_USER_DOWNLOADS_ERROR = 'app/User/GET_USER_DOWNLOADS_ERROR';

export const CREATE_USER_BEGIN = 'app/User/CREATE_USER_BEGIN';
export const CREATE_USER_SUCCESS = 'app/User/CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'app/User/CREATE_USER_ERROR';

export const UPDATE_USER_BEGIN = 'app/User/UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'app/User/UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'app/User/UPDATE_USER_ERROR';

export const DELETE_USER_BEGIN = 'app/User/DELETE_USER_BEGIN';
export const DELETE_USER_SUCCESS = 'app/User/DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'app/User/DELETE_USER_ERROR';

export const UPDATE_FIELD_DATA_BEGIN = 'app/User/UPDATE_FIELD_DATA_BEGIN';
export const UPDATE_FIELD_DATA_SUCCESS = 'app/User/UPDATE_FIELD_DATA_SUCCESS';
export const UPDATE_FIELD_DATA_ERROR = 'app/User/UPDATE_FIELD_DATA_ERROR';

export const EXPORT_USERS_BEGIN = 'app/User/EXPORT_USERS_BEGIN';
export const EXPORT_USERS_SUCCESS = 'app/User/EXPORT_USERS_SUCCESS';
export const EXPORT_USERS_ERROR = 'app/User/EXPORT_USERS_ERROR';

export const GET_SAMPLE_IMPORT_BEGIN = 'app/User/GET_SAMPLE_IMPORT_BEGIN';
export const GET_SAMPLE_IMPORT_SUCCESS = 'app/User/GET_SAMPLE_IMPORT_SUCCESS';
export const GET_SAMPLE_IMPORT_ERROR = 'app/User/GET_SAMPLE_IMPORT_ERROR';

export const GET_USER_DOWNLOAD_DATA_BEGIN = 'app/User/GET_USER_DOWNLOAD_DATA_BEGIN';
export const GET_USER_DOWNLOAD_DATA_SUCCESS = 'app/User/GET_USER_DOWNLOAD_DATA_SUCCESS';
export const GET_USER_DOWNLOAD_DATA_ERROR = 'app/User/GET_USER_DOWNLOAD_DATA_ERROR';

export const GET_USER_PROTOTYPE_BEGIN = 'app/User/GET_USER_PROTOTYPE_BEGIN';
export const GET_USER_PROTOTYPE_SUCCESS = 'app/User/GET_USER_PROTOTYPE_SUCCESS';
export const GET_USER_PROTOTYPE_ERROR = 'app/User/GET_USER_PROTOTYPE_ERROR';

export const USER_UNMOUNT = 'app/User/USER_UNMOUNT';
