/*
 *
 * Group categories constants
 *
 */


export const GET_GROUP_CATEGORIES_BEGIN = 'app/Group/GroupCategories/GET_GROUP_CATEGORIES_BEGIN';
export const GET_GROUP_CATEGORIES_SUCCESS = 'app/Group/GroupCategories/GET_GROUP_CATEGORIES_SUCCESS';
export const GET_GROUP_CATEGORIES_ERROR = 'app/Group/GroupCategories/GET_GROUP_CATEGORIES_ERROR';

export const CREATE_GROUP_CATEGORIES_BEGIN = 'app/Group/GroupCategories/CREATE_GROUP_CATEGORIES_BEGIN';
export const CREATE_GROUP_CATEGORIES_SUCCESS = 'app/Group/GroupCategories/CREATE_GROUP_CATEGORIES_SUCCESS';
export const CREATE_GROUP_CATEGORIES_ERROR = 'app/Group/GroupCategories/CREATE_GROUP_CATEGORIES_ERROR';

export const UPDATE_GROUP_CATEGORIES_BEGIN = 'app/Group/GroupCategories/UPDATE_GROUP_CATEGORIES_BEGIN';
export const UPDATE_GROUP_CATEGORIES_SUCCESS = 'app/Group/GroupCategories/UPDATE_GROUP_CATEGORIES_SUCCESS';
export const UPDATE_GROUP_CATEGORIES_ERROR = 'app/Group/GroupCategories/UPDATE_GROUP_CATEGORIES_ERROR';

export const ADD_GROUP_CATEGORIES_BEGIN = 'app/Group/GroupCategories/ADD_GROUP_CATEGORIES_BEGIN';
export const ADD_GROUP_CATEGORIES_SUCCESS = 'app/Group/GroupCategories/ADD_GROUP_CATEGORIES_SUCCESS';
export const ADD_GROUP_CATEGORIES_ERROR = 'app/Group/GroupCategories/ADD_GROUP_CATEGORIES_ERROR';

export const DELETE_GROUP_CATEGORIES_BEGIN = 'app/Group/GroupCategories/DELETE_GROUP_CATEGORIES_BEGIN';
export const DELETE_GROUP_CATEGORIES_SUCCESS = 'app/Group/GroupCategories/DELETE_GROUP_CATEGORIES_SUCCESS';
export const DELETE_GROUP_CATEGORIES_ERROR = 'app/Group/GroupCategories/DELETE_GROUP_CATEGORIES_ERROR';

export const UPDATE_GROUP_CATEGORY_TYPE_BEGIN = 'app/Group/GroupCategories/UPDATE_GROUP_CATEGORY_TYPE_BEGIN';
export const UPDATE_GROUP_CATEGORY_TYPE_SUCCESS = 'app/Group/GroupCategories/UPDATE_GROUP_CATEGORY_TYPE_SUCCESS';
export const UPDATE_GROUP_CATEGORY_TYPE_ERROR = 'app/Group/GroupCategories/UPDATE_GROUP_CATEGORY_TYPE_ERROR';

export const CATEGORIES_UNMOUNT = 'app/Group/GroupCategories/CATEGORIES_UNMOUNT';
