- name: Install logrotate
  apt:
    pkg: logrotate
    state: present

- name: update nginx logrotate config
  template:
    src: logrotate.nginx
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root

- name: update app logrotate config
  template:
    src: logrotate.rails
    dest: /etc/logrotate.d/rails
    owner: root
    group: root

- name: add rotation to daily cron
  template:
    src: logrotate.cron
    dest: /etc/cron.daily/logrotate
    owner: root
    group: root
