- name: Purging previous Rsyslog versions
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 0
  with_items:
    - rsyslog-gnutls
    - rsyslog

- name: Install Rsyslog custom repository for v8 on Ubuntu <= 14.04
  apt_repository:
    repo: "{{ loggly.rsyslog_apt_repository }}"
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|float < 16.04

- name: Cleanup older apt repositories on Ubuntu > 14.04
  apt_repository:
    repo: "{{ loggly.rsyslog_apt_repository }}"
    state: absent
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version|float >= 16.04

- name: Install Rsyslog with TLS
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    force: yes
    cache_valid_time: 0
  with_items:
    - rsyslog-gnutls
    - rsyslog

- name: Disable $KLogPermitNonKernelFacility configuration (this option is deprecated)
  lineinfile:
    dest: /etc/rsyslog.conf
    state: absent
    regexp: '^\$KLogPermitNonKernelFacility'

- name: Set a larger max message size
  lineinfile:
    dest: /etc/rsyslog.conf
    line: '$MaxMessageSize 250k'
