/*
 *
 * Mentorship constants
 *
 */

export const GET_MENTORSHIP_USERS_BEGIN = 'app/Mentorship/GET_MENTORSHIP_USERS_BEGIN';
export const GET_MENTORSHIP_USERS_SUCCESS = 'app/Mentorship/GET_MENTORSHIP_USERS_SUCCESS';
export const GET_MENTORSHIP_USERS_ERROR = 'app/Mentorship/GET_MENTORSHIP_USERS_ERROR';

export const GET_MENTORSHIP_USER_BEGIN = 'app/Mentorship/GET_MENTORSHIP_USER_BEGIN';
export const GET_MENTORSHIP_USER_SUCCESS = 'app/Mentorship/GET_MENTORSHIP_USER_SUCCESS';
export const GET_MENTORSHIP_USER_ERROR = 'app/Mentorship/GET_MENTORSHIP_USER_ERROR';

export const UPDATE_MENTORSHIP_USER_BEGIN = 'app/Mentorship/UPDATE_MENTORSHIP_USER_BEGIN';
export const UPDATE_MENTORSHIP_USER_SUCCESS = 'app/Mentorship/UPDATE_MENTORSHIP_USER_SUCCESS';
export const UPDATE_MENTORSHIP_USER_ERROR = 'app/Mentorship/UPDATE_MENTORSHIP_USER_ERROR';

export const MENTORSHIP_USER_UNMOUNT = 'app/Mentorship/MENTORSHIP_USER_UNMOUNT';
