/*
 *
 * User constants
 *
 */

export const GET_MENTORSHIP_USERS_BEGIN = 'app/User/GET_MENTORSHIP_USERS_BEGIN';
export const GET_MENTORSHIP_USERS_SUCCESS = 'app/User/GET_MENTORSHIP_USERS_SUCCESS';
export const GET_MENTORSHIP_USERS_ERROR = 'app/User/GET_MENTORSHIP_USERS_ERROR';

export const GET_MENTORSHIP_USER_BEGIN = 'app/User/GET_MENTORSHIP_USER_BEGIN';
export const GET_MENTORSHIP_USER_SUCCESS = 'app/User/GET_MENTORSHIP_USER_SUCCESS';
export const GET_MENTORSHIP_USER_ERROR = 'app/User/GET_MENTORSHIP_USER_ERROR';

export const CREATE_USER_BEGIN = 'app/User/CREATE_USER_BEGIN';
export const CREATE_USER_SUCCESS = 'app/User/CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'app/User/CREATE_USER_ERROR';

export const UPDATE_USER_BEGIN = 'app/User/UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'app/User/UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'app/User/UPDATE_USER_ERROR';

export const DELETE_USER_BEGIN = 'app/User/DELETE_USER_BEGIN';
export const DELETE_USER_SUCCESS = 'app/User/DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'app/User/DELETE_USER_ERROR';

export const UPDATE_FIELD_DATA_BEGIN = 'app/User/UPDATE_FIELD_DATA_BEGIN';
export const UPDATE_FIELD_DATA_SUCCESS = 'app/User/UPDATE_FIELD_DATA_SUCCESS';
export const UPDATE_FIELD_DATA_ERROR = 'app/User/UPDATE_FIELD_DATA_ERROR';

export const USER_UNMOUNT = 'app/User/USER_UNMOUNT';
