/*
 *
 * HomePage constants
 *
 */

export const REQUEST_PASSWORD_RESET_BEGIN = 'app/SignUp/REQUEST_PASSWORD_RESET_BEGIN';
export const REQUEST_PASSWORD_RESET_SUCCESS = 'app/SignUp/REQUEST_PASSWORD_RESET_SUCCESS';
export const REQUEST_PASSWORD_RESET_ERROR = 'app/SignUp/REQUEST_PASSWORD_RESET_ERROR';

export const GET_USER_BY_TOKEN_BEGIN = 'app/SignUp/GET_USER_BY_TOKEN_BEGIN';
export const GET_USER_BY_TOKEN_SUCCESS = 'app/SignUp/GET_USER_BY_TOKEN_SUCCESS';
export const GET_USER_BY_TOKEN_ERROR = 'app/SignUp/GET_USER_BY_TOKEN_ERROR';

export const SUBMIT_PASSWORD_BEGIN = 'app/SignUp/SUBMIT_PASSWORD_BEGIN';
export const SUBMIT_PASSWORD_SUCCESS = 'app/SignUp/SUBMIT_PASSWORD_SUCCESS';
export const SUBMIT_PASSWORD_ERROR = 'app/SignUp/SUBMIT_PASSWORD_ERROR';

export const SIGN_UP_UNMOUNT = 'app/SignUp/SIGN_UP_UNMOUNT';
